# fly.toml file generated for ecash-dice on 2024-03-07T15:42:52-07:00

app = "ecash-dice"
primary_region = "ord"

[build]
    image = "registry.fly.io/ecash-dice:latest"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
